# ==========================================
# RandomItemPVP - 数据库配置模块
# ==========================================
# 此文件包含数据库相关配置
# 如果启用模块化配置，此文件会覆盖主配置文件中的数据库设置
# ==========================================

# 数据库设置（存储玩家统计数据）
# 数据库类型：SQLITE 或 MYSQL
type: SQLITE

# SQLite 设置（type=SQLITE时使用）
sqlite:
  file: 'plugins/RandomItemPVP/data.db'  # 数据库文件路径

# MySQL 设置（type=MYSQL时使用）
mysql:
  host: 'localhost'           # 数据库地址
  port: 3306                  # 数据库端口
  database: 'randomitempvp'   # 数据库名
  username: 'root'            # 用户名
  password: 'password'        # 密码
  
  # 连接参数（高级设置）
  properties:
    useSSL: false                     # 是否使用SSL
    autoReconnect: true               # 自动重连
    serverTimezone: 'Asia/Shanghai'   # 服务器时区
    allowPublicKeyRetrieval: true     # 允许公钥检索（MySQL 8.0+必须）
    useTimezone: true                 # 使用时区
  
  # 连接池设置（HikariCP）
  pool:
    maximum-pool-size: 10             # 最大连接数
    minimum-idle: 2                   # 最小空闲连接数
    connection-timeout: 30000         # 连接超时（毫秒）
    idle-timeout: 600000              # 空闲超时（毫秒）
    max-lifetime: 1800000             # 最大生命周期（毫秒）



